### ISSUE TITLE
Change the error message from failed DLL load

### ISSUE THREAD

**Issue by greglandrum** [rdkit/knime-rdkit#13]
Instead of suggesting that the user un-install and re-install the nodes, it should provide the link to the VS2010 redistributables so that they can fix the problem.

**Comment by greglandrum** [comment]
To help understand the changes that are coming:

Currently on a windows 10 machines without the VS2010 redistributables installed, I get the results of following this error path:
https://github.com/rdkit/knime-rdkit/blob/d5cc88517fd15e35f06350d1de8f3f433b31a084/org.rdkit.knime.types/rdkit-chemsrc/org/rdkit/knime/RDKitTypesPluginActivator.java#L342

That's clearly the wrong one.

**Comment by manuelschwarze** [comment]
I just checked on my Windows 10 64-bit machine, which runs the latest KNIME RDKit Nightly Build Nodes, and there I find many different VS C++ Redistributables installed (2005, 2008, 2012, 2013) as well as Microsoft Visual Studio 2010 Tools for Office Runtime (x64), but no explicit VS C++ 2010 Redistributable. And still, all tests are running through fine for me.

When you say "changes that are coming"... are you referring to new RDKit code that I do not have yet with the KNIME RDKit nodes? 

Or could it be that the RDKit is also satisfied with some other VS C++ Redistributable, one of the ones installed on my machine? 

What exactly should we tell a user on a Windows system, if the error path is hitting the one you linked at above?

**Comment by greglandrum** [comment]
You likely got the VS2010 DLLs with the visual studio tools. 

"Changes that are coming" was an aspirational idea that I was going to fix this on my own and submit a PR. I (obviously) didn't manage to do that yet.

What we should do is direct 32bit users to this page:
https://www.microsoft.com/en-us/download/details.aspx?id=5555
and 64bit users to this page:
https://www.microsoft.com/de-de/download/details.aspx?id=14632
