### ISSUE TITLE
Add Conformers Node: multi-threading

### ISSUE THREAD

**Issue by kienerj** [rdkit/knime-rdkit#14]
A great enhancement would be to make this node multi-threaded. Currently it only uses 1 thread. With a 8-core CPU you could hence be near than 8-times faster.

**Comment by manuelschwarze** [comment]
Agreed. I looked at the source code and do not see any reason not to do this in the moment. Will have a look soon. Thanks for pointing this out.

**Comment by greglandrum** [comment]
Yeah, there's certainly no backend reason not to allow it. The underlying C++ is thread safe (and tested that way).

**Comment by greglandrum** [comment]
Thanks for pointing it out @kienerj !

**Comment by greglandrum** [comment]
@manuelschwarze : I just looked through the code here and realized that this is one that's going to be a lot quicker for you to fix than me. I was unable to figure out why this is running single threaded, but I guess you'll immediately know.
