### ISSUE TITLE
NumHeavyAtoms in Descriptor Calculation node wrong - Edge Case?

### ISSUE THREAD

**Issue by kienerj** [rdkit/knime-rdkit#33]
There seems to be an edge-case in the calculation of number of heavy atoms when using attachment points [*] in SMILES and hydrogens in brackets. Below "table" contains the smiles, the NumHeavyAtoms and MQN12 which also is heavy atom count also from Descriptor Calculation node. Here they differ and MQN12 is right while NumHeavyAtoms is wrong:

[H] | 1 | 0
[H][\*] | 2 | 0
[H]C#CC[\*] | 4 | 3
C[\*] | 2 | 1
CC[\*] | 3 | 2
OCC[\*] | 4 | 3

So it seems anything in brackets is counted as heavy atom even if it is a hydrogen or attachment point / any atom (the attachment point as [*] is copied like this from ChemDraw). At the same time MQN12 gets it right in all cases.

Not sure this is the right place to post as it probably is an issue within RDKit itself and not the KNIME node?

**Comment by greglandrum** [comment]
I don't think it's a problem with the RDKit itself:
```
In [3]: Descriptors.HeavyAtomCount(Chem.MolFromSmiles('[H][H]'))
Out[3]: 0

In [4]: Descriptors.HeavyAtomCount(Chem.MolFromSmiles('[H][*]'))
Out[4]: 0

In [5]: Descriptors.HeavyAtomCount(Chem.MolFromSmiles('[H]C'))
Out[5]: 1

In [6]: Descriptors.HeavyAtomCount(Chem.MolFromSmiles('[H]C[*]'))
Out[6]: 1
```
From looking at the code that calculates that, nothing has changed in quite a while.

Looks like this is a problem in the RDKit-KNIME code. Thanks for pointing it out!
