### ISSUE TITLE
AdjustQueryProperties() node to prepare molecules for substructure queries

### ISSUE THREAD

**Issue by greglandrum** [rdkit/knime-rdkit#4]
Here's a blog post describing the functionality:
http://rdkit.blogspot.ch/2016/07/tuning-substructure-queries-ii.html

**Comment by greglandrum** [comment]
A forum post where something similar is requested:
https://tech.knime.org/forum/rdkit/substructure-search-and-fused-rings

**Comment by manuelschwarze** [comment]
This is done in pull request merge_nibr_2016-12-16
